kind: Service # 指定创建资源的角色/类型
apiVersion: v1 # 指定api版本，此值必须在kubectl api-versions中
metadata: # 资源的元数据/属性
  name: sayHello-service # 资源的名字，在同一个namespace中必须唯一
  namespace: aha-service # 部署在哪个namespace中
spec:
  selector: # 选择器
    app: sayHello
  type: NodePort # NodePort 类型
  ports:
    - port: 9901 # service 端口
      targetPort: 9901 # 容器暴露的端口
      nodePort: 30901 # 容器开发对外的端口
      protocol: TCP # 协议
      name: http # 端口名称
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sayHello # 资源的名字，在同一个namespace中必须唯一
  namespace: aha-service # 部署在哪个namespace中
  labels:
    app: sayHello
spec:
  replicas: 1 # 声明副本数目
  revisionHistoryLimit: 1 # 保留历史版本
  selector:
    matchLabels:
      app: sayHello
  template:
    metadata:
      labels:
        app: sayHello
    spec:
      imagePullSecrets: # 镜像仓库拉取密钥
        - name: pipeline-docker-registry
      containers:
        - name: sayHello # 容器的名字
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE} # 容器使用的镜像地址
